export const CARDATA = 'CARDATA';
export const SELECTMAKE = 'SELECTMAKE';
export const VALUEMAKE = 'VALUEMAKE';
export const MODELCAR = 'MODELCAR';
export const MODELCARLIST = 'MODELCARLIST';

export const MODELCARSELECT = 'MODELCARSELECT';
export const MODELCARCHANGE = 'MODELCARCHANGE';
export const DETAILMODEL = 'DETAILMODEL';

export const MAKEMODEL = 'MAKEMODEL';
